### ISSUE TITLE
Adding https to the website

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Website#15]
We need to add https to the website.

**Comment by AnXh3L0** [comment]
To do this, you need to modify the A records for the domain at your domain name provider (I suppose Namecheap) and add 4 records as stated in this GitHub Help page: https://help.github.com/articles/setting-up-an-apex-domain/

After that, we can easily enforce HTTPS from the GitHub repo settings.

**Comment by rskikuli** [comment]
Many many thanks @AnXh3L0 . Working on this and will update the issue.

**Comment by rskikuli** [comment]
Adding @kominoshja here

**Comment by kominoshja** [comment]
I added SSL. @sidorelauku can you check this? https://www.whynopadlock.com/results/cdc419e5-9467-4dda-99ee-6d81c58664ca

**Comment by kominoshja** [comment]
@sidorelauku @rskikuli full ssl now active
